---
- name: Restart Nginx service
  ansible.builtin.service:
    name: '{{ service_name }}'
    state: restarted
  listen: restart_nginx

- name: Reload Nginx service
  ansible.builtin.service:
    name: '{{ service_name }}'
    state: reloaded
  listen: reload_nginx
