---
- name: Manage services - Install and configure
  hosts: all
  gather_facts: true
  tags:
    - always
  roles:
    - role: acme.service_management.service_installer
      tags:
        - package
        - install
    - role: acme.service_management.service_controller
      tags:
        - service
        - manage
