---
galaxy_info:
  author: Ansible Automation
  description: Role for installing nginx package
  company: Acme
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - '8'
        - '9'
  tags:
    - package
    - nginx
    - webserver

dependencies: []
