---
# Tasks for installing system packages

- name: Update apt cache on Debian-based systems
  ansible.builtin.apt:
    cache_valid_time: "{{ cache_valid_time }}"
    update_cache: "{{ update_package_cache }}"
  when:
    - ansible_os_family == 'Debian'
    - update_package_cache | bool
  tags:
    - package
    - package_install

- name: Install packages on Debian-based systems
  ansible.builtin.apt:
    name: "{{ packages_to_install }}"
    state: "{{ package_state }}"
  when: ansible_os_family == 'Debian'
  tags:
    - package
    - package_install

- name: Install packages on RedHat-based systems
  ansible.builtin.yum:
    name: "{{ packages_to_install }}"
    state: "{{ package_state }}"
  when: ansible_os_family == 'RedHat'
  tags:
    - package
    - package_install