---
- name: Service manager role
  tags:
    - service
    - service_manager

- name: Perform daemon reload if requested
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: daemon_reload | bool
  tags:
    - service
    - daemon

- name: Manage service state
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
    state: "{{ service_state }}"
    enabled: "{{ service_enabled }}"
  register: service_result
  tags:
    - service
    - state

- name: Display service state
  ansible.builtin.debug:
    msg: "Service {{ service_name }} is now {{ service_state }} and enabled={{ service_enabled }}"
  tags:
    - service
    - debug
