---
- name: Restart service
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
    state: restarted
    daemon_reload: true
  listen: restart service

- name: Reload service
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
    state: reloaded
  listen: reload service

- name: Enable service
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
    enabled: true
  listen: enable service
