---
galaxy_info:
  author: 'Ansible Automation'
  description: 'Role for deploying and managing Nginx web server'
  company: 'ACME'
  license: 'GPL-3.0-or-later'
  min_ansible_version: 2.15.0
  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
  tags:
    - webserver
    - nginx
    - service
    - package
dependencies: []
