galaxy_info:
  author: Ansible Automation
  description: Role for installing nginx package
  company: ACME
  license: Apache-2.0
  min_ansible_version: "2.15.0"
  galaxy_tags:
    - package
    - nginx
    - installation

dependencies: []
