---
- name: Ensure Nginx service is in desired state
  become: true
  ansible.builtin.service:
    name: "{{ nginx_service_name }}"
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
  tags:
    - service_manage
    - nginx
