---
- name: Restart nginx service
  ansible.builtin.service:
    name: "{{ ngix_service_name }}"
    state: restarted
  listen: restart nginx
  tags:
    - nginx
    - service

- name: Reload nginx service
  ansible.builtin.service:
    name: "{{ ngix_service_name }}"
    state: reloaded
  listen: reload nginx
  tags:
    - nginx
    - service