galaxy_info:
  author: Ansible Collection Generator
  description: Role for installing packages on target systems
  company: Acme
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: EL
      versions:
        - '8'
        - '9'
    - name: Debian
      versions:
        - bullseye
        - bookworm
dependencies: []