---
galaxy_info:
  author: Ansible Automation
  description: Role for installing system packages
  company: ACME
  license: GPL-3.0-or-later
  min_ansible_version: '2.15.0'
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

dependencies: []
