---
- name: Update package cache on Debian-based systems
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ package_installer_cache_valid_time }}"
  when:
    - ansible_os_family == 'Debian'
    - package_installer_update_cache | bool
  tags:
    - package
    - package_installer

- name: Install/manage packages on Debian-based systems
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ package_installer_packages }}"
  when:
    - ansible_os_family == 'Debian'
    - package_installer_packages is defined
    - package_installer_packages | length > 0
  tags:
    - package
    - package_installer

- name: Install/manage packages on RedHat-based systems
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ package_installer_packages }}"
  when:
    - ansible_os_family == 'RedHat'
    - package_installer_packages is defined
    - package_installer_packages | length > 0
  tags:
    - package
    - package_installer
