---
- name: Restart nginx service
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: restarted
  listen: restart nginx

- name: Reload nginx service
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: reloaded
  listen: reload nginx
